<a href="https://colab.research.google.com/github/KateFilippova/DLS_2022_basic/blob/main/DLS2022_HW2%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>


<h3 style="text-align: center;"><b>Школа глубокого обучения ФПМИ МФТИ, осень 2021</b></h3>

## Домашнее задание: библиотека Numpy и линейная алгебра


In [1]:
import numpy as np
import random
import scipy.stats as sps

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [5]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))

# Выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?

# ========
# Ваш код здесь
# ========
print(a.ndim)
print(b.shape)

2
(100, 100)


In [35]:
a

array([0.22601708, 0.76816949, 0.89131618])

In [22]:
def mult(a, b):
    """  
    a: list of "size" lists, each contains "size" floats --- первая матрица-аргумент
    b: list of "size" lists, each contains "size" floats --- вторая матрица-аргумент
    return c: list of "size" lists, each contains "size" floats --- матрица, являющаяся результатом умножения матриц a и b
    
    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c 

    Реализуйте умножение матриц без использования функций из пакета numpy
    """
    result = 0
    res_matrix = []
    for i in range(0, len(a)):
      row = a[i]
      res_row = []
      for j in range(0, len(b)):
        result = 0
        col = b.T[j]
        for n in range(0, len(row)):
          result += row[n]*col[n]
        res_row.append(result)
      res_matrix.append(res_row)



    return res_matrix

In [ ]:
mult(a, b)

In [25]:
def np_mult(a, b):
    """  
    a: np.array[size, size]             --- первая матрица-аргумент
    b: np.array[size, size] --- вторая матрица-аргумент
    return c: np.array[size, size]       --- матрица, являющаяся результатом умножения матриц a и b
    
    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c 

    Реализуйте умножение матриц, используя функции из пакета numpy
    """
    return np.dot(a, b)
    

In [24]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 350 ms, sys: 5.51 ms, total: 355 ms
Wall time: 357 ms


In [26]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 1.63 ms, sys: 2.02 ms, total: 3.64 ms
Wall time: 7.61 ms


In [27]:
# проверим корректность
assert np.allclose(np.array(M1), M2)

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [28]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.22601708 0.76816949 0.89131618] [0.52884901 0.88503706 0.85548447]


In [30]:
def scalar_product(a, b):
    """  
    a: np.array[, n] --- первая матрица-аргумент длиной n
    b: np.array[, n] --- вторая матрица-аргумент длиной n
    return c: float  --- результат скалярного произведения векторов a и b

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению a x b = c 

    Реализуйте скалярное умножение векторов, не используя функции из пакета numpy

    """ 
    res = 0
    for i in range(0, len(a)):
      res += a[i]*b[i]
    return res

In [29]:
def np_scalar_product(a,b):
    """  
    a: np.array[, n] --- первая матрица-аргумент
    b: np.array[, n] --- вторая матрица-аргумент
    return c: float  --- результат скалярного произведения векторов a и b

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению a x b = c 

    Реализуйте скалярное умножение векторов, используя функции из пакета numpy
    """ 
    return np.dot(a, b)

In [31]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)

# проверим корректность:
assert np.allclose(product_1, product_2)

CPU times: user 22 µs, sys: 0 ns, total: 22 µs
Wall time: 25.3 µs
CPU times: user 50 µs, sys: 0 ns, total: 50 µs
Wall time: 53.2 µs


Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

------------------

**Ответ:** Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Задание 3
Напишите функцию, которая находим сумму четных диагональных элементов квадратной матрицы. Если таких элементов нет, то вывести `0`. Используйте библиотеку Numpy

In [42]:
def np_diag_2k(a):
    """  
    a: np.array[m, m] --- первая матрица-аргумент
    return c: float   --- сумма элементов массива а, принадлежащих диагонали и являющимися четными

    Функция принимает на вход квадратную матрицу размерностью m x m и возвращает число,
    равное сумме четных диагональных элементов этой квадратной матрицы

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    diag = a.diagonal()
    return np.sum(diag[diag % 2 == 0])

In [40]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[6, 3, 9, 7, 1],
       [1, 1, 2, 7, 2],
       [5, 1, 6, 7, 3],
       [8, 6, 5, 6, 1],
       [6, 5, 4, 6, 6]])

In [38]:
a[0,0]

9

In [43]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 128 µs, sys: 13 µs, total: 141 µs
Wall time: 149 µs


24

### Задание 4
​
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $(x = (x_1, x_2, \ldots, x_n)$ массива $X$ строит строчку $s = (s_1, s_2, \ldots, s_n)$,  где $s_k=x_1+...+x_k$, а затем выдаёт массив из построенных строчек. Используйте библиотеку <code>numpy</code> (вам поможет функция <code>cumsum</code>). Выходом функции должен быть двумерный <code>numpy</code>-массив той же формы, что и $X$.
​ 

In [44]:
A = sps.uniform.rvs(size=10**3) 

In [49]:
A

array([3.24451873e-01, 1.48599372e-01, 3.16641661e-01, 1.71706594e-02,
       2.99728637e-01, 3.93893513e-01, 8.50612397e-01, 7.71945278e-01,
       9.80012289e-01, 8.23546074e-01, 8.03805814e-01, 5.03460175e-01,
       4.21105602e-02, 8.70011025e-01, 3.17043512e-01, 6.20626497e-01,
       3.49074297e-02, 1.89329368e-01, 5.75268090e-01, 5.43068763e-01,
       5.68555402e-01, 1.04730167e-01, 3.59168830e-01, 9.19141676e-01,
       5.46200991e-01, 8.59553463e-01, 7.43543999e-01, 2.97808740e-01,
       1.26755055e-01, 6.93252634e-01, 1.84904511e-01, 1.71582720e-01,
       8.40344059e-01, 4.84701471e-01, 8.23447827e-01, 5.53468435e-01,
       9.51984630e-01, 9.30287224e-01, 8.16995698e-02, 4.39894145e-01,
       9.55043697e-01, 8.10017669e-01, 8.71379516e-01, 2.45102265e-01,
       2.35328600e-01, 3.89615094e-01, 1.66571061e-01, 8.18918484e-01,
       4.97084709e-01, 4.09411524e-01, 8.53902319e-02, 2.23487690e-01,
       9.50882665e-01, 4.11902178e-01, 9.83399141e-01, 8.97039889e-01,
      

In [52]:
def cumsum(A):
    """  
    A: np.array[num_row, num_column]        --- матрица-аргумент
    return S: np.array[num_row, num_column] --- выходная матрица кумулятивных сумм

    Функция принимает на вход матрицу A размерностью n x m и возвращает 
    матрицу с той же размерностью n x m, i-ая строчка которой есть последовательность 
    кумулятивных сумм элементов i-ой строки матрицы A

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    # return np.cumsum(A,axis=1)
    return np.cumsum(A)
    

In [53]:
# зададим некоторую последовательность и проверим ее на вашей функции. 
A = sps.uniform.rvs(size=10**3) 

%time S2 = cumsum(A)

CPU times: user 45 µs, sys: 5 µs, total: 50 µs
Wall time: 54.4 µs


### Задание 5

​
Задан двумерный массив $X$. Для каждой строчки массива X необходимо сделать следующее преобразование.

Пусть дана строчка x. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число a (значение по умолчанию a=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив x с преобразованным x и вывести.

Напишите функцию, которая выполняет данное преобразование для каждой строчки двумерного массива X. Массив X при этом должен остаться без изменений.

Используйте библиотеку numpy.

Пример:
$X = [[100,200,300,400,500]]$ -> $[[100,a,300,a,500]]$ -> $[[500^3,a,300^3,a,100^3]]$ -> склеиваем -> $[[100,200,300,400,500,500^3,a,300^3,a,100^3]]$

​

In [95]:
from copy import copy
def np_transformation(X, a=1):
    """  
    X: np.array[num_row, num_column]          --- матрица-аргумент
    a: float                                  --- значение для преобразования нечетных элементов строк в X
    return S: np.array[num_row, num_column*2] --- матрица, где строки являются 
    сконкатенированными строками изначальной матрицы X со строками, являющимися их преобразованиями

    Функция принимает на вход матрицу X размерностью n x m, число a и 
    возвращает  матрицу с размерностью n x m*2, i-ая строчка которой является склеенной
    i-ой строкой X с ее преобразованием ее строки transformation(X[i]), записанном в обратном порядке, 
    где преобразование для числа k определено как:
    transformation(k) = a if ind(k) % 2 == 0 else k**3

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    M = copy(X)
    for i in M:
      i[1:len(i):2] = a
      i[0:len(i):2] = i[0:len(i):2]**3

      # np.flip(i, axis=1)
    X = np.append(X, np.flip(M))
    return X

In [56]:
X = np.array([[i for i in range(1, 10, 2)]])
%time S2 = np_transformation(X, 5)

CPU times: user 64 µs, sys: 0 ns, total: 64 µs
Wall time: 133 µs


In [96]:
X = np.array([[i for i in range(1, 10, 2)]])
X

array([[1, 3, 5, 7, 9]])

In [97]:
np_transformation(X, 5)

array([  1,   3,   5,   7,   9, 729,   5, 125,   5,   1])

### Задание 6
Написать функцию для кодирование массива (Run-length encoding). Все подряд идущие повторения элементов функция сжимает в один элемент и считает количество повторений этого элемента. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить. 

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [9]:
def np_encode(a):
    """  
    a: np.array[, n] --- вектор-аргумент длиной n
    return (elems, repetitions): (np.array, np.array) --- выходной кортеж из вектора 
    элементов и вектора их количеств в подряд идущих повторениях

    Функция принимает на вход вектор a длиной n, добавляет в вектор elem сжатые 
    в один элемент подряд идущие повторения элементов входного вектора a, в вектор 
    repetitions добавляет длины последовательностей подряд идущих повторений. 
    Затем функция возвращает кортеж векторов (elems, repetitions).

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    el1 = a[np.nonzero(np.diff(a, prepend=0))]
    if np.diff(X, prepend=0)[-1] == 0:
      el2 = np.append(np.diff(np.nonzero(np.diff(X, prepend=0))), len(a) - np.nonzero(np.diff(X, prepend=0))[0][-1])
    else:
      el2 = np.diff(np.nonzero(np.diff(X, prepend=0)))


    return (el1, el2)

In [5]:
# np.diff(np.nonzero(np.insert(np.diff(X), 0, 1)))
np.diff(np.nonzero(np.diff(X, prepend=0)))

array([[1, 2, 2, 2, 2, 1]])

In [6]:
np.diff(X, prepend=0)

array([ 1,  1,  0,  1,  0, -2,  0,  4,  0, -3,  1,  0])

In [7]:
np.diff(X, prepend=0)[-1]

0

In [10]:
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

%time x, num = np_encode(X)

CPU times: user 451 µs, sys: 0 ns, total: 451 µs
Wall time: 498 µs


In [11]:
x, num

(array([1, 2, 3, 1, 5, 2, 3]), array([1, 2, 2, 2, 2, 1, 2]))

In [12]:
def encode(a):
    
    el1 = a[np.nonzero(np.insert(np.diff(a), 0, 1))]
    if np.insert(np.diff(a), 0, 1)[-1] == 0:
        
#         el2 = np.diff(np.nonzero(np.insert(np.diff(a), 0, 1)))
    
        el2 = np.append(np.diff(np.nonzero(np.insert(np.diff(a), 0, 1))), len(a) - np.nonzero(np.insert(np.diff(a), 0, 1))[0][-1])
    else:
        el2 = np.diff(np.nonzero(np.insert(np.diff(a), 0, 1)))


    return (el1, el2)